app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    path('', include('order.urls')),
    path('', include('products.urls')),

] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
) + debug_toolbar_urls()

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('order/pay/<int:pk>', views.PayView.as_view(), name='pay'),
    path('order/save_order/', views.SaveOrderView.as_view(), name='save_order'),
    path('order/list/', views.ListOrderView.as_view(), name='list_order'),
    path('order/detail_order/<int:pk>',
         views.DetailOrderView.as_view(), name='detail_order'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('addtocart/', views.AddToCartView.as_view(), name='addtocart'),
    path('removetocart/', views.RemoveToCartView.as_view(), name='removetocart'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('purchasesummary/', views.PurchaseSummaryView.as_view(),
         name='purchasesummary'),
    path('<slug>/', views.ProductDetailView.as_view(), name='detail'),

]

user_profile/urls.py
from django.urls import path
from . import views


app_name = 'user_profile'

urlpatterns = [
    path('user_profile/create/', views.CreateView.as_view(), name='create'),
    path('user_profile/update/', views.UpdateView.as_view(), name='update'),
    path('user_profile/login/', views.LoginView.as_view(), name='login'),
    path('user_profile/logout/', views.LogoutView.as_view(), name='logout'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    total = models.FloatField()
    total_quantity = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self) -> str:
        return f'Pedido N. {self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    quantity = models.IntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self) -> str:
        return f'Item do {self.order}'

    class Meta:
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Itens'

order/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from products.models import Variation
from utils import utils
from .models import Order, OrderItem


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('user_profile:create')
        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(user=self.request.user)
        return queryset


class PayView(DispatchLoginRequiredMixin, DetailView):
    template_name = 'order/pay.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'


class SaveOrderView(View):
    template_name = 'order/pay.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(self.request, 'Você precisa fazer Login!')
            return redirect('user_profile:create')

        if not self.request.session.get('cart'):
            messages.error(self.request, 'Carrinho vazio!')
            return redirect('product:list')

        cart = self.request.session.get('cart')
        variation_cart_ids = [v for v in cart]
        variation_db = list(Variation.objects.select_related('product').filter(
            id__in=variation_cart_ids))

        for variation in variation_db:
            vid = str(variation.id)
            stock = variation.stock
            qtd_cart = cart[vid]['quantity']
            unit_price = cart[vid]['unit_price']
            promotional_price = cart[vid]['unit_promotional_price']

            error_msg_stock = ''

            if stock < qtd_cart:
                cart[vid]['quantity'] = stock
                cart[vid]['quantitative_price'] = stock * unit_price
                cart[vid]['quantitative_promotional_price'] = stock * \
                    promotional_price

                error_msg_stock = 'Estoque insuficiente para alguns produtos do seu carrinho, a quantidade deles foi reduzida. Verifique os produtos a seguir.'
                messages.error(
                    self.request, error_msg_stock)

                self.request.session.save()
                return redirect('product:cart')

        total_cart_quantity = utils.total_cart_quantity(cart)
        cart_total = utils.total_cart(cart)

        order = Order(
            user=self.request.user,
            total=cart_total,
            total_quantity=total_cart_quantity,
            status='C',
        )

        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_price'],
                    promotional_price=v['quantitative_promotional_price'],
                    quantity=v['quantity'],
                    image=v['image'],
                ) for v in cart.values()
            ]
        )
        del self.request.session['cart']
        # return render(self.request, self.template_name, context)
        return redirect(reverse('order:pay', kwargs={'pk': order.pk}))


class DetailOrderView(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'order/detail.html'
    pk_url_kwarg = 'pk'


class ListOrderView(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/list.html'
    paginate_by = 5
    ordering = ['-id']

templates/partials/_cart.html
{% load static %}
{% load omfilters %}
<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>Variação</th>
            <th>QTD.</th>
            <th>Preço Unit.</th>
            <th>Total</th>
        </tr>

        {% for item in request.session.cart.values %}
            <tr>
                <td class="d-none d-lg-block">
                    <img class="cart-img" src="{% get_media_prefix %}{{ item.image }}">
                </td>
                <td>
                    <a href="{% url 'product:detail' item.slug %}">
                        {{ item.product_name }}
                    </a>
                    <a class="ml-3" href="{% url 'product:removetocart' %}?vid={{ item.variation_id }}">
                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                    </a>
                </td>
                <td>{{ item.variation_name }}</td>
                <td>{{ item.quantity }}</td>
                {% if item.unit_promotional_price %}
                    <td>{{ item.unit_promotional_price|format_price }}</td>
                {% else %}
                    <td>{{ item.unit_price|format_price }}</td>
                {% endif %}

                {% if item.quantitative_promotional_price %}
                    <td>{{ item.quantitative_promotional_price|format_price }}</td>
                {% else %}
                    <td>{{ item.quantitative_price|format_price }}</td>
                {% endif %}
            </tr>
        {% endfor %}


    </table>
</div>

templates/partials/_footer.html
{% load static %}
<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Luiz Otávio</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/partials/_head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/_nav.html
{% load omfilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'product:list' %}">E-commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Conta
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'user_profile:create' %}">Atualizar meus dados</a>
                    <a class="dropdown-item" href="{% url 'order:list_order' %}">Meus pedidos</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'user_profile:logout' %}">Sair</a>
                </div>
            </li>
            {% else %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_profile:create' %}">Entrar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_profile:create' %}">Criar Conta</a>
            </li>
            {% endif %}

            {% if request.session.cart %}
                <li class="nav-item">
                    <a class="nav-link nav-cart-link active" href="{% url 'product:cart' %}">
                        <span class="nav-cart-text mr-1">
                            Carrinho
                        </span>
                        <span class="nav-cart-count mr-1">
                            <strong>{{ request.session.cart|total_cart_quantity }}x</strong>
                        </span>
                        <span class="nav-cart-icon mr-2">
                            <i class="fas fa-shopping-cart"></i>
                        </span>
                    </a>
                </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'product:search' %}">
            <input name="term" value="{{ request.GET.term }}" class="form-control mr-sm-2" type="search" placeholder="Busca" aria-label="Busca">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Busca</button>
        </form>
    </div>
</nav>

templates/partials/_order.html
{% load static %}
{% load omfilters %}

<div class="row">
    <div class="col">
        <h3>{{ order }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ order.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ order.total|format_price }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ order.total_quantity }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ order.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for line in order.orderitem_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ line.image }}">
                    </td>
                    <td>{{ line.product }}</td>
                    <td>{{ line.variation }}</td>
                    <td>{{ line.quantity }}</td>
                    <td>
                        {% if line.promotional_price %}
                        {{ line.promotional_price|format_price }}
                        {% else %}
                        {{ line.price|format_price }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

templates/partials/_pagination.html
{% if is_paginated %}
<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}