app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    path('', include('order.urls')),
    path('', include('products.urls')),

] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
) + debug_toolbar_urls()

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('order/pay/<int:pk>', views.PayView.as_view(), name='pay'),
    path('order/save_order/', views.SaveOrderView.as_view(), name='save_order'),
    path('order/list/', views.ListOrderView.as_view(), name='list_order'),
    path('order/detail_order/<int:pk>',
         views.DetailOrderView.as_view(), name='detail_order'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    total = models.FloatField()
    total_quantity = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self) -> str:
        return f'Pedido N. {self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=255)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    quantity = models.IntegerField()
    image = models.CharField(max_length=2000)

    def __str__(self) -> str:
        return f'Item do {self.order}'

    class Meta:
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Itens'

order/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from products.models import Variation
from utils import utils
from .models import Order, OrderItem


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('user_profile:create')
        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(user=self.request.user)
        return queryset


class PayView(DispatchLoginRequiredMixin, DetailView):
    template_name = 'order/pay.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'


class SaveOrderView(View):
    template_name = 'order/pay.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(self.request, 'Você precisa fazer Login!')
            return redirect('user_profile:create')

        if not self.request.session.get('cart'):
            messages.error(self.request, 'Carrinho vazio!')
            return redirect('product:list')

        cart = self.request.session.get('cart')
        variation_cart_ids = [v for v in cart]
        variation_db = list(Variation.objects.select_related('product').filter(
            id__in=variation_cart_ids))

        for variation in variation_db:
            vid = str(variation.id)
            stock = variation.stock
            qtd_cart = cart[vid]['quantity']
            unit_price = cart[vid]['unit_price']
            promotional_price = cart[vid]['unit_promotional_price']

            error_msg_stock = ''

            if stock < qtd_cart:
                cart[vid]['quantity'] = stock
                cart[vid]['quantitative_price'] = stock * unit_price
                cart[vid]['quantitative_promotional_price'] = stock * \
                    promotional_price

                error_msg_stock = 'Estoque insuficiente para alguns produtos do seu carrinho, a quantidade deles foi reduzida. Verifique os produtos a seguir.'
                messages.error(
                    self.request, error_msg_stock)

                self.request.session.save()
                return redirect('product:cart')

        total_cart_quantity = utils.total_cart_quantity(cart)
        cart_total = utils.total_cart(cart)

        order = Order(
            user=self.request.user,
            total=cart_total,
            total_quantity=total_cart_quantity,
            status='C',
        )

        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=v['product_name'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_price'],
                    promotional_price=v['quantitative_promotional_price'],
                    quantity=v['quantity'],
                    image=v['image'],
                ) for v in cart.values()
            ]
        )
        del self.request.session['cart']
        # return render(self.request, self.template_name, context)
        return redirect(reverse('order:pay', kwargs={'pk': order.pk}))


class DetailOrderView(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'order/detail.html'
    pk_url_kwarg = 'pk'


class ListOrderView(DispatchLoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/list.html'
    paginate_by = 5
    ordering = ['-id']

order/templates/order/detail.html
{% extends 'base.html' %}
{% load static %}
{% load omfilters %}

{% block title %}{{ order }} | {% endblock title %}

{% block content %}

{% include 'partials/_order.html' %}

{% endblock %}

order/templates/order/list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}Pedidos de {{ user }} | {% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{ user }}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for order in orders %}
                <tr>
                    <th scope="row">{{ order }}</td>
                    <td>{{ order.total|format_price }}</td>
                    <td>{{ order.total_quantity }}</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>
                        <a href="{% url 'order:detail_order' order.pk %}">
                            Ver <i class="fas fa-search-plus ml-2"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}


            </table>
        </div>
    </div>
</div>

{% include 'partials/_pagination.html' %}

{% endblock %}

order/templates/order/pay.html
{% extends 'base.html' %}

{% load static %}
{% load omfilters %}

{% block title %}Pagamento | {% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>

{% include 'partials/_order.html' %}

<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>


{% endblock %}