app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    path('', include('order.urls')),
    path('', include('products.urls')),

] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
) + debug_toolbar_urls()

order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('order/pay/<int:pk>', views.PayView.as_view(), name='pay'),
    path('order/save_order/', views.SaveOrderView.as_view(), name='save_order'),
    path('order/list/', views.ListOrderView.as_view(), name='list_order'),
    path('order/detail_order/<int:pk>',
         views.DetailOrderView.as_view(), name='detail_order'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='list'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('addtocart/', views.AddToCartView.as_view(), name='addtocart'),
    path('removetocart/', views.RemoveToCartView.as_view(), name='removetocart'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('purchasesummary/', views.PurchaseSummaryView.as_view(),
         name='purchasesummary'),
    path('<slug>/', views.ProductDetailView.as_view(), name='detail'),

]

user_profile/urls.py
from django.urls import path
from . import views


app_name = 'user_profile'

urlpatterns = [
    path('user_profile/create/', views.CreateView.as_view(), name='create'),
    path('user_profile/update/', views.UpdateView.as_view(), name='update'),
    path('user_profile/login/', views.LoginView.as_view(), name='login'),
    path('user_profile/logout/', views.LogoutView.as_view(), name='logout'),
]

products/models.py
from django.conf import settings
from django.db import models
from PIL import Image
import os
from django.utils.text import slugify
from utils import utils


class Product(models.Model):
    name = models.CharField(max_length=255)
    short_description = models.TextField(max_length=255)
    long_description = models.TextField(max_length=255)
    image = models.ImageField(
        upload_to='product_images/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    price_marketing = models.FloatField(verbose_name='Price')
    price_promotional_marketing = models.FloatField(
        default=0, verbose_name='Price Prom.')
    type = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variação'),
            ('S', 'Simples')
        )
    )

    def get_price_marketing_formated(self):
        return utils.format_price(self.price_marketing)
    get_price_marketing_formated.short_description = 'Price'

    def get_price_promotional_marketing_formated(self):
        return utils.format_price(self.price_promotional_marketing)
    get_price_promotional_marketing_formated.short_description = 'Price Prom.'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = int(round(new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height),
                                 Image.Resampling.LANCZOS)
        new_img.save(img_full_path, optimize=True, quality=50)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.name)
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.image:
            self.resize_image(self.image, max_image_size)

    def __str__(self):
        return self.name


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    stock = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.name or self.product.name

products/views.py
from django.shortcuts import render, redirect, resolve_url, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views import View
from products.models import Product, Variation
from django.contrib import messages
from django.db.models import Q
from user_profile.models import UserProfile


class ProductListView(ListView):
    model = Product
    template_name = 'products/list.html'
    context_object_name = 'products'
    paginate_by = 10
    ordering = ['-id']


class SearchView(ProductListView):
    def get_queryset(self, *args, **kwargs):
        term = self.request.GET.get('term') or self.request.session['term']
        queryset = super().get_queryset(*args, **kwargs)

        if not term:
            return queryset

        self.request.session['term'] = term

        queryset = queryset.filter(
            Q(name__icontains=term) |
            Q(short_description__icontains=term) |
            Q(long_description__icontains=term)
        )

        self.request.session.save()
        return queryset


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'product'
    slug_field = 'slug'


class AddToCartView(View):

    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER', resolve_url('product:list'))

        variation_id = self.request.GET.get('vid')

        if not variation_id:
            messages.error(self.request, 'Produto não existe!')
            return redirect(http_referer)

        variation = get_object_or_404(Variation, id=variation_id)

        variation_stock = variation.stock
        product = variation.product

        product_id = product.id  # type: ignore
        product_name = product.name
        variation_name = variation.name or ''
        unit_price = variation.price
        unit_promotional_price = variation.promotional_price
        quantity = 1
        slug = product.slug
        image = product.image

        if image:
            image = image.name
        else:
            image = ''

        if variation.stock < 1:
            messages.error(
                self.request, 'Estoque insuficiente!'
            )
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            self.request.session['cart'] = {}
            self.request.session.save()

        cart = self.request.session['cart']

        if variation_id in cart:
            cart_quantity = cart[variation_id]['quantity']
            cart_quantity += 1

            if variation_stock < cart_quantity:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {
                        cart_quantity}x no produto "{product_name}".'
                    f'Adicionamos {variation_stock}x no seu carrinho.'
                )
                cart_quantity = variation_stock

            cart[variation_id]['quantity'] = cart_quantity
            cart[variation_id]['quantitative_price'] = unit_price * cart_quantity
            cart[variation_id]['quantitative_promotional_price'] = unit_promotional_price * cart_quantity
        else:
            cart[variation_id] = {
                'product_id': product_id,
                'product_name': product_name,
                'variation_name': variation_name,
                'variation_id': variation_id,
                'unit_price': unit_price,
                'unit_promotional_price': unit_promotional_price,
                'quantitative_price': unit_price,
                'quantitative_promotional_price': unit_promotional_price,
                'quantity': quantity,
                'slug': slug,
                'image': image,
            }

        self.request.session.save()

        messages.success(
            self.request,
            f'Produto {product.name} {
                variation_name} adicionado ao seu carrinho,'
            f' total de {cart[variation_id]['quantity']} unidades!'
        )
        return redirect(http_referer)


class RemoveToCartView(View):

    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER', resolve_url('product:list'))
        variation_id = self.request.GET.get('vid')

        if not variation_id:
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            return redirect(http_referer)

        if variation_id not in self.request.session['cart']:
            return redirect(http_referer)

        cart = self.request.session['cart'][variation_id]

        messages.warning(
            self.request,
            f'Produto {cart["product_name"]} {cart['variation_name']} '
            f'removido com sucesso do seu pedido!'
        )

        del self.request.session['cart'][variation_id]
        self.request.session.save()
        return redirect(http_referer)


class CartView(View):

    def get(self, *args, **kwargs):
        context = {'cart': self.request.session.get('cart', {})}
        return render(self.request, 'products/cart.html', context)


class PurchaseSummaryView(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('user_profile:create')

        profile = UserProfile.objects.filter(
            user_profile=self.request.user).exists()

        if not profile:
            messages.error(self.request, 'Usuário sem perfil')
            return redirect('user_profile:create')

        if not self.request.session.get('cart'):
            messages.error(self.request, 'Carrinho vazio!')
            return redirect('product:list')

        context = {
            'user': self.request.user,
            'cart': self.request.session['cart'],
        }
        return render(self.request, 'products/purchasesummary.html', context)

products/templates/products/cart.html
{% extends "base.html" %}
{% load omfilters %}
{% block title %}Carrinho | {% endblock title %}
{% block content %}

{% if cart %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

            {% include 'partials/_cart.html' %}
        </div>
    </div>



    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{ cart|total_cart|format_price }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'product:purchasesummary' %}">
                Finalizar a compra
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'user_profile:create' %}">
                Finalizar a compra
            </a>
            {% endif %}
        </div>
    </div>

{% else %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho vazio</h3>
            <p class="lead">Não há produtos em seu carrinho.</p>
        </div>
    </div>

{% endif %}


{% endblock content %}

products/templates/products/detail.html
{% extends "base.html" %}
{% load omfilters %}

{% block title %}{{product.name}} | {% endblock title %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        {% if product.image %}
                        <img class="img-fluid" src="{{ product.image.url }}">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{ product.name }}</h1>
                    <p class="lead">{{ product.short_description }}</p>
                    <p class="lead">
                        {% if product.price_promotional_marketing %}
                        <span id="variation-preco-promocional" class="lead product-price">{{ product.price_promotional_marketing|format_price }}</span>
                        <span id="variation-preco"
                            class="lead product-old-price text-muted">{{ product.price_marketing|format_price }}</span>
                        {% else %}
                        <span id="variation-preco" class="lead product-price">{{ product.price_marketing|format_price }}</span>
                        {% endif %}
                    </p>

                    
                    <form action="{% url 'product:addtocart' %}" id="form-add-to-cart">
                        <div class="form-group">
                            <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                {% for variate in product.variation_set.all %}

                                {% if variate.promotional_price %}

                                <option data-preco="{{ variate.price|format_price }}" data-preco-promocional="{{ variate.promotional_price|format_price  }}" 
                                    value="{{ variate.id }}">
                                    {% if variate.name %}
                                    {{ variate.name }}
                                    {% else %}
                                    {{ variate }}
                                    {% endif %}
                                </option>

                                {% else %}
                                <option data-preco-promocional="{{ variate.price|format_price }}" value="{{ variate.id }}">
                                    {% if variate.name %}
                                    {{ variate.name }}
                                    {% else %}
                                    {{ variate }}
                                    {% endif %}
                                </option>

                                {% endif %}

                                {% endfor %}
                            </select>
                        </div>
                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>

                    </form>
                    

                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">{{ product.name }}</h2>
                    <p>{{ product.long_description|linebreaks }}</p>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

products/templates/products/list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}Home | {% endblock title %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for product in products %}
                <div class="card">

                    {% if product.image %}
                    <a href="{% url 'product:detail' product.slug %}">
                        <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </a>
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.short_description }}</p>
                        <div class="container product-price-block text-center">

                            {% if product.price_promotional_marketing %}
                                <span class="product-price">
                                    {{ product.price_promotional_marketing|format_price }}
                                </span>
                                <span class="product-old-price text-muted">
                                    {{ product.price_marketing|format_price }}
                                </span>
                            {% else %}
                                <span class="product-price">
                                    {{ product.price_marketing|format_price }}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top-light-custom text-center">
                        <a href="{% url 'product:detail' product.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Comprar
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        {% include 'partials/_pagination.html' %}
    </div>
</div>
{% endblock %}

products/templates/products/purchasesummary.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}Resumo da compra | {% endblock title %}

{% block content %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'user_profile:create' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ user.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ user.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ user.userprofile.age}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ user.userprofile.date_of_birth }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ user.userprofile.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ user.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'user_profile:create' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ user.userprofile.address }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ user.userprofile.address_number }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ user.userprofile.complement }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ user.userprofile.neighbourhood }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ user.userprofile.city }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ user.userprofile.state }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ user.userprofile.cep }}</dd>
        </dl>
    </div>
</div>



<div class="row mt-3">
    <div class="col">
        <h3>Resumo do carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

         {% include 'partials/_cart.html' %}
    </div>

</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center"><span class="font-weight-bold">Total do carrinho:</span>
            {{ cart|total_cart|format_price }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'order:save_order' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>

{% endblock %}